<?php

/**
*
* @package BB3Chat
* @copyright (c) 2015 PPK
* @license http://opensource.org/licenses/gpl-2.0.php GNU General Public License v2
*
*
*/

if (!defined('IN_PHPBB'))
{
	exit;
}
if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

$lang = array_merge($lang, array(
	'BB3CHAT' => 'Chat',
	'BB3CHAT_GUEST' => 'Guest',

	'CHAT_EXIT' => 'Esci dalla chat',
        'CHAT_ENTER' => 'Entra nella chat',
        'CHAT_MESSAGE' => 'Messaggio',
        'CHAT_RESET' => 'Cancella',
        'CHAT_SEND' => 'Invia',
        'CHAT_LOGIN' => 'Vai alla chat',
        'CHAT_IN' => 'Chat',
        'CHAT_CANT_VIEWCHATU' => 'Tu <strong> non puoi </strong> vedere gli utenti nella chat',
        'CHAT_CANT_VIEWCHATM' => 'Tu <strong> non puoi </strong> vedere i messaggi di chat',
        'CHAT_CANT_ADDCHATM' => 'Tu <strong> non puoi </strong> aggiungere messaggi di chat',
        'CHAT_LA_CHECK' => 'Sei stato rimosso dalla chat',
        'CHAT_DELMESS' => 'Elimina messaggio',
        'CHAT_LANG_ERROR' => 'Nessun file di lingua trovato',
        'CHAT_PM' => 'PM',
        'CHAT_PMHLP' => 'Attiva la modalità messaggio privato',
        'CHAT_PMIN' => '<i class="fa fa-user" aria-hidden="true"></i> <strong> messaggio privato da </strong>',
        'CHAT_TOYOU' => '<i class="fa fa-arrow-circle-o-right" aria-hidden="true"></i> <strong> ti scrive </strong>',
        'CHAT_PMOUT' => '<i class="fa fa-user" aria-hidden="true"></i> <strong> messaggio privato per </strong>',
        'CHAT_PMFOR' => '<strong> per </strong>',
        'CHAT_PMFROM' => '<strong> da </strong>',
        'CHAT_KICK' => 'K',
        'CHAT_BAN' => 'B',
        'CHAT_UNBAN' => 'U',
        'CHAT_QUICKBAN' => 'Q',
        'CHAT_KICK_TEXT' => 'Rimuovi dalla chat',
        'CHAT_BAN_TEXT' => 'Ban',
        'CHAT_UNBAN_TEXT' => 'Unban',
        'CHAT_QUICKBAN_TEXT' => 'Brutto rapido',
        'CHAT_KICKHLP' => 'Rimuovi utente dalla chat',
        'CHAT_BANHLP' => 'Escludi utente',
        'CHAT_UNBANHLP' => 'Unban utente',
        'CHAT_QUICKBANHLP' => 'Banna rapido utente ed elimina tutti i suoi messaggi',
        'CHAT_SETHIDDENHLP' => 'Abilita modalità invisibile',
        'CHAT_BANNED' => 'Sei bannato dalla chat con %s',
        'CHAT_REFRESH' => 'Non puoi aggiornare e/o entrare in chat prima del ritardo impostato',
        'CHAT_UBANNED' => 'Bannato dalla chat fino al %s',
        'CHAT_UKICK' => 'Rimuovi utente dalla chat',
        'CHAT_UUNBAN' => 'Unban utente',
	'CHAT_ERRDESCR' => array(
		1 => 'Sei stato bannato nella chat dall amministratore.',
                2 => 'Non puoi inviare un messaggio alla chat prima del ritardo impostato.',
                3 => 'NON puoi leggere e aggiungere messaggi alla chat.',
                4 => 'Sei stato rimosso dalla chat per inattività.',
                5 => 'Sei stato rimosso dalla chat dall amministratore.',
                6 => 'Stai già chattando.',
                7 => 'Non sei connesso alla chat.',
	),
	'CHAT_PMUSER_EXITED' => 'L utente a cui stai inviando un messaggio privato ha lasciato la chat, inviare il messaggio alla chat generale?',
        'CHAT_DELETE' => 'Elimina',
        'CHAT_DELETE_USERS' => 'Rimuovi utenti dalla chat',
        'CHAT_DELETE_MESS' => 'Elimina messaggi chat',
        'CHAT_DELETE_AMESS' => 'Elimina archivio dei messaggi di chat',
        'CHAT_MCLEAN' => 'tutti i messaggi',
        'CHAT_UCLEAN' => 'utenti',
        'CHAT_ACLEAN' => 'archivio',
        'CHAT_ARCHIVE' => 'Archivi',
        'CHAT_VIEW_ARCHIVE' => 'visualizza',
        'CHAT_DISPLAY_OPT' => 'Visualizza',
        'CHAT_HIDE_ARCHIVE' => 'nascondi',
        'CHAT_TUPDATE' => '<strong>Aggiorna </strong>: ogni [<strong>%d</strong>] secondi',
        'CHAT_HEIGHT' => 'Altezza',
        'CHAT_TEXT_SIZE' => 'Testo',
        'CHAT_TEXT_PSIZE' => 'Aumenta la dimensione del testo',
        'CHAT_TEXT_MSIZE' => 'Riduci la dimensione del testo',
        'CHAT_MHEIGHT' => 'Diminuisci altezza della chat',
        'CHAT_PHEIGHT' => 'Aumenta altezza della chat',
        'CHAT_OHEIGHT' => 'Ripristina altezza chat',
        'CHAT_CHATKEY_ERROR' => 'Errore durante la creazione della chiave della chat...',
        'CHAT_ARCH_EMPTY' => 'Non ci sono messaggi in archivio.',
        'CHAT_USER_ADM' => 'Amministra utente',
        'CHAT_TO_USER' => 'Contatta utente',
        'CHAT_EDIT' => 'Modifica',
        'CHAT_EDIT_CANCEL' => 'Annulla',
        'CHAT_EDITED_BY' => '&nbsp;(modificato <a href="%1$s" title="%3$s">%2$s</a>)',
        'CHAT_WAIT_MESSAGES' => 'Aspetta, i messaggi verranno caricati tra <strong>%d</strong> secondi ..',
        'CHAT_AJAX_ERROR' => 'Errore: impossibile creare oggetto XmlHttpRequest. Aggiorna il tuo browser o usane un altro. ',
        'CHAT_SOUND_SWITCH' => 'Attiva la notifica sonora di nuovi messaggi',
        'CHAT_SORT_SWITCH' => 'Abilita la visualizzazione di nuovi messaggi dal basso',
        'CHAT_DISABLED' => 'La chat è disconnessa',
        'CHAT_GUEST_DISABLED' => 'La chat per gli ospiti è disabilitata, registrati e/o accedi al forum',
        'CHAT_WINDOW' => 'Nella finestra pop-up',
        'CHAT_CLOSE' => 'chiudi',
        'CHAT_HIDE_USERS' => 'Nascondi &quot; In chat&quot;',
        'CHAT_HIDE_SMILES' => 'Nascondi emoticon',
        'CHAT_HIDE_BBCODES' => 'Nascondi BBCodes',
        'CHAT_STOP_SCROLL' => 'Non scorrere automaticamente i messaggi',
        'CHAT_STOP_REFRESH' => 'Non aggiorna automaticamente i messaggi',
        'CHAT_ACT_INDICATOR' => 'Indicatore di aggiornamento',
        'CHAT_AUTO_REFRESH' => 'Aggiornamento automatico',
        'CHAT_MANUAL_REFRESH' => 'Aggiornamento manuale',
        'CHAT_NEW_MESSAGE' => 'Nuovo messaggio',

	'MESSAGE_EDIT_ERROR' => 'Il messaggio non esiste o non ha diritti di modifica.',
        'MESS_DEL' => 'Elimina messaggio',
        'MESS_EDIT' => 'Modifica messaggio',

        'UBAN_TIME' => 'Escludi utente per il numero di ore specificato (non più di 1000)',
        'UBAN_CONFIRM' => 'Band utente su',
        'UBAN_CONFIRM2' => '',
        'UBAN_CONFIRM3' => 'ore',

        'BBCHAT_B' => 'Testo in grassetto [b]testo[/b]',
        'BBCHAT_I' => 'Testo in corsivo [i]testo[/i]',
        'BBCHAT_U' => 'Testo sottolineato [u]testo[/u]',
        'BBCHAT_S' => 'Testo barrato [s]testo[/s]',
        'BBCHAT_COLOR' => 'Testo in un altro colore [color=color]testo[/color], nome colore (rosso) o codice alfanumerico FF0000',
        'BBCHAT_SIZE' => 'Testo in una dimensione diversa [size=size]text[/size], dimensione dal 50 al 200%',
        'BBCHAT_URL' => 'Collega [url]link[/url] o [url=link]testo[/url]',
        'BBCHAT_Q' => 'Citazione [quote]testo[/quote]',
        'BBCHAT_CODE' => 'Codice sorgente del programma/script [code][noparse]text[/noparse][/code]',
	// 'BBCHAT_NOPARSE' => 'Text with disabling bb codes [noparse] text with bb codes [/noparse]',
	'BBCHAT_IMG' => 'Image [img=link to image][/img]',
	'IP' => 'IP',
	'PAGE' => 'Page',
	'CHAT_UADMIN' => 'Administration',
	'IN_CHAT' => 'Chatting',
	'CHAT_ITS_YOU' => 'It\'s you',
	'DATA_PERIOD_SHORT' => array ('y' => 'g.', 'm' => 'month.', 'd' => 'd.', 'h' => 'hour.', 'i' => 'min.', 's' => 'sec.'),

	'datetime' => array(
		'TODAY' => 'Today',
		'TOMORROW' => 'Tomorrow',
		'YESTERDAY' => 'Yesterday',
		'AGO' => array(
			0 => 'less than a minute ago',
			1 => '%d minute ago',
			2 => '%d minutes ago',
			3 => '%d minutes ago',
		),

		'Sunday' => 'Sunday',
		'Monday' => 'Monday',
		'Tuesday' => 'Tuesday',
		'Wednesday' => 'Wednesday',
		'Thursday' => 'Thursday',
		'Friday' => 'Friday',
		'Saturday' => 'Saturday',

		'Sun' => 'Sun',
		'Mon' => 'Mon',
		'Tue' => 'Tue',
		'Wed' => 'Wed',
		'Thu' => 'Thu',
		'Fri' => 'Fri',
		'Sat' => 'Sat',

		'January' => 'January',
		'February' => 'February',
		'March' => 'March',
		'April' => 'April',
		'May' => 'May',
		'June' => 'June',
		'July' => 'July',
		'August' => 'August',
		'September' => 'September',
		'October' => 'October',
		'November' => 'November',
		'December' => 'December',

		'Jan' => 'Jan',
		'Feb' => 'Feb',
		'Mar' => 'mar',
		'Apr' => 'Apr',
		'May_short' => 'may', // Short representation of "May". May_short used because in English the short and long date are the same for May.
		'Jun' => 'jun',
		'Jul' => 'Jul',
		'Aug' => 'Aug',
		'Sep' => 'sen',
		'Oct' => 'oct',
		'Nov' => 'nov',
		'Dec' => 'dec',
	),
));
