<?php

/**
*
* @package BB3Chat
* @copyright (c) 2015 PPK
* @license http://opensource.org/licenses/gpl-2.0.php GNU General Public License v2
*
*
*/

if (!defined('IN_PHPBB'))
{
	exit;
}
if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

$lang = array_merge($lang, array(
	'ACP_BB3CHAT' => 'BB3Chat',
	'ACP_BB3CHAT_EXPLAIN' => 'Settings',
	'ACP_BB3CHAT_CONFIG' => 'Settings',

	'BB3CHAT_ENABLE' => 'Enable chat',
	'BB3CHAT_ENABLE_OFF' => 'turn off',
	'BB3CHAT_ENABLE_ON' => 'enable',
	'BB3CHAT_ENABLE_AUTO' => 'enable with auto-login',
	'BB3CHAT_ENABLE_READ' => 'read mode',
	'BB3CHAT_ENABLE_EXPLAIN' => 'Allow chat, two options,
		<br /><strong> option 1 </strong> enable chat, with auto-login: the user will enter the chat automatically, read mode: if the user is not logged in to the chat, only the chat message window will be displayed,
		<br /><strong> option 2 </strong> full mode of operation, if enabled, the chat will display all user data of messages that are in the chat, otherwise only the data of users who are in the chat ',
	'BB3CHAT_GUESTS' => 'Chat for guests',
	'BB3CHAT_GUESTS_BYIP' => 'By IP address',
	'BB3CHAT_GUESTS_BYSESSION' => 'By session ID',
	'BB3CHAT_GUESTS_EXPLAIN' => 'Two options,
		<br /><strong> option 1 </strong> allow unregistered users to use chat,
		<br /><strong> option 2 </strong> method of determining guests, when determining by IP address, all users with the same IP address will be considered as one user ',
	'BB3CHAT_GUESTS_OPTION' => 'Chat options for guests',
	'BB3CHAT_GUESTS_OPTION_EXPLAIN' => 'Three options,
		<br /><strong> option 1 </strong> chat language for guests (this option will be applied only for reading mode),
		<br /><strong> option 2 </strong> the maximum number for random selection and adding chat guests to nicknames of users, the number will be selected from the range [1-value specified in this option],
		<br /><strong> option 3 </strong> the username of the guests in the chat, it can be a language variable or an ordinary string ',
	'BB3CHAT_WAITTIME' => 'Delay sending messages',
	'BB3CHAT_WAITTIME_EXPLAIN' => 'After sending a message, the send message button is blocked for the specified time',
	'BB3CHAT_INACTIVE_TIME' => 'Inactivity time',
	'BB3CHAT_INACTIVE_TIME_EXPLAIN' => 'Time after which the user will be considered to have left the chat',
	'BB3CHAT_MESSLENGTH' => 'Length of chat message',
	'BB3CHAT_MESSLENGTH_EXPLAIN' => 'Messages longer than this value will be truncated (no more than 255)',
	'BB3CHAT_MUREFRESH' => 'Update chat window',
	'BB3CHAT_MUREFRESH_EXPLAIN' => 'Update time of the message list window and chat users (at least 10 seconds)',
	'BB3CHAT_MESSDISPLAY' => 'Number of chat messages',
	'BB3CHAT_MESSDISPLAY_EXPLAIN' => 'Display this number of recent chat messages',
	'BB3CHAT_CLEANUP_INTERVAL' => 'Clear old messages',
	'BB3CHAT_CLEANUP_INTERVAL_EXPLAIN' => 'Two options,
		<br /><strong> option 1 </strong> frequency of deleting old messages from chat,
		<br /><strong> option 2 </strong> consider messages dated older than specified ',
	'BB3CHAT_KILLTIME' => 'Removing inactive users',
	'BB3CHAT_KILLTIME_EXPLAIN' => 'Remove inactive (not leaving messages) users from chat during this time',
	'BB3CHAT_MARCHIVE' => 'Message archive',
	'BB3CHAT_MARCHIVE_EXPLAIN' => 'Display the specified number of messages in the archive (0 - do not display the archive), messages larger than those specified in the "input" option will be considered archived "',
	'BB3CHAT_MAXSMILES' => 'Maximum number of emoticons',
	'BB3CHAT_MAXSMILES_EXPLAIN' => 'The maximum number of emoticons in one chat message (set 0 to disable the restriction)',
	'BB3CHAT_UMCLEAN' => 'Clearing the list of users, messages',
	'BB3CHAT_UMCLEAN_EXPLAIN' => 'Four options,
		<br /><strong> option 1 </strong> delete all users of their chat (except banned ones),
		<br /><strong> option 2 </strong> unban all banned users,
		<br /><strong> option 3 </strong> delete obsolete chat messages (except archived messages),
		<br /><strong> option 4 </strong> delete archived messages from chat ',
	'BB3CHAT_AUTOKILL_ONPOST' => 'Auto eject when sending',
	'BB3CHAT_AUTOKILL_ONPOST_EXPLAIN' => 'Automatically drop a user from the chat if his message was sent to the chat before the set delay in the option <u> Delay sending messages </u>',
	'BB3CHAT_AUTOKILL_ONREFRESH' => 'Auto eject when updating',
	'BB3CHAT_AUTOKILL_ONREFRESH_EXPLAIN' => 'Automatically drop a user from the chat if the chat page is updated with a previously set delay in the <u> Update chat window </u> option',
	'BB3CHAT_ENABLE_PM' => 'Private chat messages',
	'BB3CHAT_ENABLE_PM_EXPLAIN' => 'Allow the use of private messages in the chat (the corresponding user rights must be assigned)',
	'BB3CHAT_ENABLE_ACOMMANDS' => 'Admin teams in chat',
	'BB3CHAT_ENABLE_ACOMMANDS_EXPLAIN' => 'Allow the use of administrator commands in the chat: delete, ban users, clear messages and users (the corresponding user rights must be assigned)',
	'BB3CHAT_QBANTIME' => 'Fast ban time',
	'BB3CHAT_QBANTIME_EXPLAIN' => 'When using the quick ban in the chat, the user will be banned for the time specified here, and all his messages will be deleted from the chat',
	'BB3CHAT_LOGS' => 'Chat action log',
	'BB3CHAT_LOGS_EXPLAIN' => 'Log in chat actions, five options,
		<br /><strong> option 1 </strong> log of user bans, unbanned users,
		<br /><strong> option 2 </strong> user deletion log,
		<br /><strong> option 3 </strong> message cleaning log, archive, user list,
		<br /><strong> option 4 </strong> log for deleting single chat messages,
		<br /><strong> option 5 </strong> chat message editing log ',
	'BB3CHAT_HEIGHT' => 'Chat height settings',
	'BB3CHAT_HEIGHT_EXPLAIN' => 'Four options,
		<br /><strong> option 1 </strong> pitch change chat height,
		<br /><strong> option 2 </strong> minimum chat height,
		<br /><strong> option 3 </strong> maximum chat height,
		<br /><strong> option 4 </strong> original chat height ',
	'BB3CHAT_ENABLE_BBCODES' => 'BB codes in the chat',
	'BB3CHAT_ENABLE_BBCODES_OFF' => 'No',
	'BB3CHAT_ENABLE_BBCODES_BASE' => 'Standard base',
	'BB3CHAT_ENABLE_BBCODES_ALL' => 'Standard all',
	'BB3CHAT_ENABLE_BBCODES_NONST' => 'Non-standard',
	'BB3CHAT_ENABLE_BBCODES_EXPLAIN' => 'Allow the use of bb codes in the chat (the corresponding user rights must be assigned)',
	'BB3CHAT_EXCLUDE_BBCODES' => 'Exclude bb codes',
	'BB3CHAT_EXCLUDE_BBCODES_EXPLAIN' => 'Do not display or process selected bb codes in the chat (only works if bb codes are used: “Standard all”), the chat automatically excludes bb codes containing java script or without tokens in the replacement string' ,
	'BB3CHAT_TRUE_EXCLUDE_BBCODES' => 'Exclude bb codes',
	'BB3CHAT_TRUE_EXCLUDE_BBCODES_EXPLAIN' => 'If Yes is selected, exclude the bb codes selected above, otherwise, include only the indicated bb codes',
	'BB3CHAT_ENABLE_MAGICURL' => 'chat URL',
	'BB3CHAT_ENABLE_MAGICURL_EXPLAIN' => 'Automatically convert www and email links to clickable',
	'BB3CHAT_URL_REPLACE' => 'Replacing links',
	'BB3CHAT_URL_REPLACE_EXPLAIN' => 'Replace www and email links with the specified text, you can use a language variable (empty line - delete the link)',
	'BB3CHAT_AVATARS' => 'Chat avatars',
	'BB3CHAT_AVATARS_EXPLAIN' => 'Display avatars in chat, two options,
		<br /><strong> option 1 </strong> 0 - do not display, a number other than 0 means the width of the avatar in pixels (the avatar function must be enabled on the forum),
		<br /><strong> option 2 </strong> default avatar (should be in the directory /ext/ppk/bb3chat/images/) ',
	'BB3CHAT_SOUNDS' => 'Chat sounds',
	'BB3CHAT_SOUNDS_OFF' => 'no',
	'BB3CHAT_SOUNDS_INCHAT' => 'not in read mode',
	'BB3CHAT_SOUNDS_ALL' => 'yes',
	'BB3CHAT_SOUNDS_EXPLAIN' => 'Sound notification of new chat messages, three options,
		<br /><strong> option 1 </strong> enable notification,
		<br /><strong> option 2 </strong> is enabled by default,
		<br /><strong> option 3 </strong> the audio file to play (should be in the directory /ext/ppk/bb3chat/sound/) ',
	'BB3CHAT_ALLOW_POST_FLASH' => 'Allow bb code [flash]',
	'BB3CHAT_ALLOW_POST_FLASH_EXPLAIN' => 'The corresponding user rights must be assigned',
	'BB3CHAT_ALLOW_POST_IMG' => 'Allow bb code [img]',
	'BB3CHAT_ALLOW_POST_IMG_EXPLAIN' => 'The corresponding user rights must be assigned',
	'BB3CHAT_ALLOW_POST_URL' => 'Allow bb code [url]',
	'BB3CHAT_ALLOW_POST_URL_EXPLAIN' => 'The corresponding user rights must be assigned',
	'BB3CHAT_ALLOW_LINKS' => 'Allow links in messages',
	'BB3CHAT_ALLOW_LINKS_LOCALEMAIL' => 'Local and email',
	'BB3CHAT_ALLOW_LINKS_EXPLAIN' => 'If you disable the option, all links when sending messages will be deleted or replaced with text from the option below (the corresponding user rights must be assigned), this option does not disable the use of links via bb code [url]',
	'BB3CHAT_ALLOW_SMILIES' => 'Allow emoticons',
	'BB3CHAT_ALLOW_SMILIES_EXPLAIN' => '',

	'LOG_CHAT_DELMESS' => '<strong> Deleted user message from chat </strong>',
	'LOG_CHAT_EDITMESS' => '<strong> Edited user chat message </strong>',
	'LOG_CHAT_UCLEAN' => '<strong> The list of chat users has been cleared </strong>',
	'LOG_CHAT_MCLEAN' => '<strong> The list of chat messages has been cleared </strong>',
	'LOG_CHAT_ACLEAN' => '<strong> Cleared the list of archive chat messages </strong>',
	'LOG_CHAT_UKICK' => '<strong> Removed user from chat </strong>',
	'LOG_CHAT_UBAN' => '<strong> The chat user has been banned </strong>',
	'LOG_CHAT_UQBAN' => '<strong> The chat user has been banned and all his chat messages have been deleted </strong>',
	'LOG_CHAT_UUNBAN' => '<strong> Chat user has been banned </strong>',
	'LOG_CONFIG_BB3CHAT_CONFIG' => '<strong> Chat settings changed </strong>',
	'ACP_CONFIG_OPTION' => 'option',

	'TSEC' => 'sec',
	'TMIN' => 'min',
	'THOUR' => 'h',
	'TDAY' => 'd',
	'DATA_PERIOD_SHORT' => array ('y' => 'g.', 'm' => 'month.', 'd' => 'd.', 'h' => 'hour.', 'i' => 'min.', 's' => 'sec.'),

	'ACL_CAT_PPKEXT' => 'PPK extensions',

	'ACL_U_CANVIEWCHATM' => '<span style="font-weight:bold;color:#C000C0;"> BB3Chat </span>: Can see chat messages',
	'ACL_U_CANVIEWCHATU' => '<span style="font-weight:bold;color:#C000C0;"> BB3Chat </span>: Can see chat users',
	'ACL_U_CANDELCHATM' => '<span style="font-weight:bold;color:#C000C0;"> BB3Chat </span>: Can delete self messages from the chat',
	'ACL_U_CANEDITCHATM' => '<span style="font-weight:bold;color:#C000C0;"> BB3Chat </span>: Can edit self chat messages',
	'ACL_U_CANADDCHATM' => '<span style="font-weight:bold;color:#C000C0;"> BB3Chat </span>: Can send messages to chat',
	'ACL_U_CANSKIPCHATKTIME' => '<span style="font-weight:bold;color:#C000C0;"> BB3Chat </span>: Can "bypass" the restrictions on the period of inactivity in the chat',
	'ACL_U_CANHIDDENINCHAT' => '<span style="font-weight:bold;color:#C000C0;"> BB3Chat </span>: May be hidden in the chat',
	'ACL_U_CANVIEWHIDDINCHAT' => '<span style="font-weight:bold;color:#C000C0;"> BB3Chat </span>: Can see hidden users in chat',
	'ACL_U_CANSENDCHATPM' => '<span style="font-weight:bold;color:#C000C0;"> BB3Chat </span>: Can send private chat messages',
	'ACL_U_CANSKIPDISBUTTON' => '<span style="font-weight:bold;color:#C000C0;"> BB3Chat </span>: May "bypass" temporarily disabling the send message button',
	'ACL_U_CANUSESMILIES' => '<span style="font-weight:bold;color:#C000C0;"> BB3Chat </span>: Can use emoticons in messages',
	'ACL_U_CANUSEURL' => '<span style="font-weight:bold;color:#C000C0;"> BB3Chat </span>: Can use links in messages',
	'ACL_U_CANUSEBBCODES' => '<span style="font-weight:bold;color:#C000C0;"> BB3Chat </span>: Can use BB codes in messages',
	'ACL_U_CANUSEBBIMG' => '<span style="font-weight:bold;color:#C000C0;"> BB3Chat </span>: Can use BB code [img] in messages',
	'ACL_U_CANUSEBBFLASH' => '<span style="font-weight:bold;color:#C000C0;"> BB3Chat </span>: Can use BB code [flash] in messages',
	'ACL_U_CANUSEBBURL' => '<span style="font-weight:bold;color:#C000C0;"> BB3Chat </span>: Can use BB code [url] in messages',
	'ACL_U_CANUSEACOMMANDS' => '<span style="font-weight:bold;color:#C000C0;"> BB3Chat </span>: Can ban and delete users, clear chat',
	'ACL_U_CANDELCHATM2' => '<span style="font-weight:bold;color:#C000C0;"> BB3Chat </span>: Can remove NOT self messages from the chat',
	'ACL_U_CANEDITCHATM2' => '<span style="font-weight:bold;color:#C000C0;"> BB3Chat </span>: Can edit NOT self chat messages',
	'ACL_U_CANVIEWARCHIVE' => '<span style="font-weight:bold;color:#C000C0;"> BB3Chat </span>: Can read chat message archive',
));
